### ISSUE TITLE
Add `name` property to `Icon` component

### ISSUE THREAD

**Issue by amir78729** [Tap30/web-components#78]
`<tap-icon-x></tap-icon-x>` → `<tap-icon name="x"></tap-icon>`

**Comment by amir78729** [comment]
@majidsajadi Please assign this to me

**Comment by majidsajadi** [comment]
@amir78729 
Im not pretty sure that this is the best approach for icon library. 
Also I suggest create another repository for the icons since we can publish the icons right now.
