### ISSUE TITLE
Add JsDoc to Components

### ISSUE THREAD

**Issue by amir78729** [Tap30/web-components#94]
- [x] `avatar`
- [x] `badge-wrapper`
- [x] `badge`
- [x] `banner`
- [x] `base-button`
- [ ] `bottom-navigation`
- [x] `button`
- [ ] `checkbox`
- [ ] `divider`
- [x] `icon-button`
- [ ] `modal`
- [ ] `progress-indicator`
- [ ] `radio-group`
- [ ] `radio`
- [ ] `row`
- [ ] `segmented-button`
- [ ] `step-indicator`
- [ ] `textfield`
- [ ] `toast`

**Comment by HamidG420** [comment]
I would like to contribute to this task.
